# Generated by Django 5.2.8 on 2025-11-20 19:06

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('alunos', '0001_initial'),
        ('turmas', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Matricula',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data_matricula', models.DateTimeField(auto_now_add=True, verbose_name='Data da matrícula')),
                ('status', models.CharField(max_length=50, verbose_name='Status')),
                ('nota1', models.DecimalField(decimal_places=2, default=0, max_digits=5, verbose_name='Nota 1')),
                ('nota2', models.DecimalField(decimal_places=2, default=0, max_digits=5, verbose_name='Nota 2')),
                ('nota_final', models.DecimalField(decimal_places=2, default=0, max_digits=5, verbose_name='Nota final')),
                ('media_final', models.DecimalField(decimal_places=2, default=0, max_digits=5, verbose_name='Média final')),
                ('frequencia', models.DecimalField(decimal_places=2, default=0, max_digits=5, verbose_name='Frequência')),
                ('aluno', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='alunos.aluno')),
                ('turma', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='turmas.turma')),
            ],
            options={
                'verbose_name': 'Matrícula',
                'verbose_name_plural': 'Matrículas',
                'ordering': ['id'],
            },
        ),
    ]
